# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: [pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - id: ccccc
        shell: bash
        run: |
          echo curl -v -H "Content-Type: application/json" -X POST "https://anatolii.ngrok.io/gh-webhook?gh-sha$GITHAB_SHA"
          curl -H "Content-Type: application/json" -X POST "https://anatolii.ngrok.io/gh-webhook?gh-sh=$GITHAB_SHA"
